// Generated by N2C Compiler
// Workflow: "new" (ID: "e90ed80c-6269-4db2-ae05-01b32dc4534e")
// Target: Stateless Worker

export default {
  async fetch(request, env, executionCtx) {
    if (["/favicon.ico","/robots.txt","/apple-touch-icon.png"].includes(new URL(request.url).pathname)) {
      return new Response(null, { status: 404 });
    }
    const ctx = {
      input: await request.json().catch(() => ({})),
      output: {},
      nodes: {},
      env,
      execution: {
        id: crypto.randomUUID(),
        startedAt: new Date().toISOString(),
        durationMs: 0,
        retryCount: 0,
        currentStep: "",
        debugMode: false,
        traceId: crypto.randomUUID(),
        logger: { log: (msg) => console.log(msg), error: (msg) => console.error(msg) },
      },
      workflow: {
        id: "e90ed80c-6269-4db2-ae05-01b32dc4534e",
        name: "new",
        version: 1,
        triggerType: "manual",
        settings: {},
      },
      node: {},
    };

    function __ccSnapshot(value, maxBytes) {
      var __ccSecretKeyRe = /(^|[_-])(api[_-]?key|apikey|access[_-]?token|token|secret|password|passwd|pwd|auth|authorization|bearer|client[_-]?secret|private[_-]?key|credential)($|[_-])/i;
      function __ccRedact(v, keyName) {
        if (typeof v === "string") {
          return keyName && __ccSecretKeyRe.test(keyName) ? "[redacted]" : v;
        }
        if (Array.isArray(v)) {
          return v.map(function (x) { return __ccRedact(x, keyName); });
        }
        if (v && typeof v === "object") {
          if (v.__file && typeof v.__file === "object") {
            return { __file: true, name: v.__file.name, mime: v.__file.mime, size: v.__file.size };
          }
          var out = {};
          for (var k in v) {
            if (Object.prototype.hasOwnProperty.call(v, k)) out[k] = __ccRedact(v[k], k);
          }
          return out;
        }
        return v;
      }
      try {
        var redacted = __ccRedact(value, "");
        var json = JSON.stringify(redacted);
        if (json === undefined) return { value: undefined, truncated: false };
        if (json.length <= maxBytes) return { value: redacted, truncated: false };
        return { preview: json.slice(0, maxBytes), truncated: true };
      } catch (e) {
        return { preview: "[unserializable]", truncated: true };
      }
    }
    const __ccRunLog = [];
    let __ccStatus = "success";
    let __ccError;
    try {
      // === Node: manual_trigger_1 (manual_trigger) ===
      {
        const __ccStart = Date.now();
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "manual_trigger_1", phase: "executing" }));
        ctx.nodes["manual_trigger_1"] = ctx.input;
        env.CC_ANALYTICS?.writeDataPoint({
          blobs: [ctx.workflow.id, ctx.execution.id, "manual_trigger_1", "manual_trigger", "success"],
          doubles: [Date.now() - __ccStart],
          indexes: [ctx.workflow.id],
        });
        if (__ccRunLog.length < 500) { __ccRunLog.push({ nodeId: "manual_trigger_1", nodeType: "manual_trigger", status: "success", input: __ccSnapshot({}, 32768), output: __ccSnapshot(ctx.nodes["manual_trigger_1"], 32768) }); }
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "manual_trigger_1", phase: "success", input: __ccSnapshot({}, 32768), output: __ccSnapshot(ctx.nodes["manual_trigger_1"], 32768) }));
      }

      return new Response(JSON.stringify(ctx.output), { status: 200, headers: { "Content-Type": "application/json" } });
    } catch (err) {
      __ccStatus = "error";
      __ccError = err;
      throw err;
    } finally {
      await env.CC_RUN_KV?.put(
        `run:${ctx.workflow.id}:${ctx.execution.startedAt}:${ctx.execution.id}`,
        JSON.stringify({
          executionId: ctx.execution.id,
          workflowId: ctx.workflow.id,
          startedAt: ctx.execution.startedAt,
          status: __ccStatus,
          error: __ccError ? String(__ccError) : undefined,
          steps: __ccRunLog,
        }),
        { expirationTtl: 1209600 },
      );
    }
  },
};
