// Generated by N2C Compiler
// Workflow: "new" (ID: "e90ed80c-6269-4db2-ae05-01b32dc4534e")
// Target: Stateless Worker

export default {
  async fetch(request, env, executionCtx) {
    if (["/favicon.ico","/robots.txt","/apple-touch-icon.png"].includes(new URL(request.url).pathname)) {
      return new Response(null, { status: 404 });
    }
    const ctx = {
      input: await request.json().catch(() => ({})),
      output: {},
      nodes: {},
      env,
      execution: {
        id: crypto.randomUUID(),
        startedAt: new Date().toISOString(),
        durationMs: 0,
        retryCount: 0,
        currentStep: "",
        debugMode: false,
        traceId: crypto.randomUUID(),
        logger: { log: (msg) => console.log(msg), error: (msg) => console.error(msg) },
      },
      workflow: {
        id: "e90ed80c-6269-4db2-ae05-01b32dc4534e",
        name: "new",
        version: 1,
        triggerType: "manual",
        settings: {},
      },
      node: {},
    };

    const __ccRunLog = [];
    let __ccStatus = "success";
    let __ccError;
    try {
      // === Node: node_1785876139401_2 (manual_trigger) ===
      {
        const __ccStart = Date.now();
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "node_1785876139401_2", phase: "executing" }));
        ctx.nodes["node_1785876139401_2"] = ctx.input;
        env.CC_ANALYTICS?.writeDataPoint({
          blobs: [ctx.workflow.id, ctx.execution.id, "node_1785876139401_2", "manual_trigger", "success"],
          doubles: [Date.now() - __ccStart],
          indexes: [ctx.workflow.id],
        });
        if (__ccRunLog.length < 500) { __ccRunLog.push({ nodeId: "node_1785876139401_2", nodeType: "manual_trigger", status: "success" }); }
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "node_1785876139401_2", phase: "success" }));
      }
      // === Node: node_1787576548290_2 (set) ===
      {
        const __ccStart = Date.now();
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "node_1787576548290_2", phase: "executing" }));
        ctx.nodes["node_1787576548290_2"] = Object.assign({}, ctx.input, (() => {
  const __ccSetPath = (obj, path, value) => {
    const parts = String(path).split(".");
    let cur = obj;
    for (let i = 0; i < parts.length - 1; i++) {
      const k = parts[i];
      if (typeof cur[k] !== "object" || cur[k] === null || Array.isArray(cur[k])) cur[k] = {};
      cur = cur[k];
    }
    cur[parts[parts.length - 1]] = value;
  };
  const __out = {};
  for (const [__k, __v] of []) { __ccSetPath(__out, __k, __v); }
  return __out;
})());
        env.CC_ANALYTICS?.writeDataPoint({
          blobs: [ctx.workflow.id, ctx.execution.id, "node_1787576548290_2", "set", "success"],
          doubles: [Date.now() - __ccStart],
          indexes: [ctx.workflow.id],
        });
        if (__ccRunLog.length < 500) { __ccRunLog.push({ nodeId: "node_1787576548290_2", nodeType: "set", status: "success" }); }
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "node_1787576548290_2", phase: "success" }));
      }

      return new Response(JSON.stringify(ctx.output), { status: 202, headers: { "Content-Type": "application/json" } });
    } catch (err) {
      __ccStatus = "error";
      __ccError = err;
      throw err;
    } finally {
      await env.CC_RUN_KV?.put(
        `run:${ctx.workflow.id}:${ctx.execution.startedAt}:${ctx.execution.id}`,
        JSON.stringify({
          executionId: ctx.execution.id,
          workflowId: ctx.workflow.id,
          startedAt: ctx.execution.startedAt,
          status: __ccStatus,
          error: __ccError ? String(__ccError) : undefined,
          steps: __ccRunLog,
        }),
        { expirationTtl: 1209600 },
      );
    }
  },
};
