// Generated by N2C Compiler
// Workflow: "New workflow" (ID: "11e34c42-83df-4f68-a78d-3de8bbb0245b")
// Target: Stateless Worker

export default {
  async fetch(request, env, executionCtx) {
    const ctx = {
      input: await request.json().catch(() => ({})),
      output: {},
      nodes: {},
      env,
      execution: {
        id: crypto.randomUUID(),
        startedAt: new Date().toISOString(),
        durationMs: 0,
        retryCount: 0,
        currentStep: "",
        debugMode: false,
        traceId: crypto.randomUUID(),
        logger: { log: (msg) => console.log(msg), error: (msg) => console.error(msg) },
      },
      workflow: {
        id: "11e34c42-83df-4f68-a78d-3de8bbb0245b",
        name: "New workflow",
        version: 1,
        triggerType: "manual",
        settings: {},
      },
      node: {},
    };

    const __ccRunLog = [];
    let __ccStatus = "success";
    let __ccError;
    try {
      // === Node: manual_trigger_1 (manual_trigger) ===
      {
        const __ccStart = Date.now();
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "manual_trigger_1", phase: "executing" }));
        ctx.nodes["manual_trigger_1"] = ctx.input;
        env.CC_ANALYTICS?.writeDataPoint({
          blobs: [ctx.workflow.id, ctx.execution.id, "manual_trigger_1", "manual_trigger", "success"],
          doubles: [Date.now() - __ccStart],
          indexes: [ctx.workflow.id],
        });
        __ccRunLog.push({ nodeId: "manual_trigger_1", nodeType: "manual_trigger", status: "success" });
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "manual_trigger_1", phase: "success" }));
      }
      // === Node: set_1 (set) ===
      {
        const __ccStart = Date.now();
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "set_1", phase: "executing" }));
        ctx.nodes["set_1"] = (() => {
  const __ccSetPath = (obj, path, value) => {
    const parts = String(path).split(".");
    let cur = obj;
    for (let i = 0; i < parts.length - 1; i++) {
      const k = parts[i];
      if (typeof cur[k] !== "object" || cur[k] === null || Array.isArray(cur[k])) cur[k] = {};
      cur = cur[k];
    }
    cur[parts[parts.length - 1]] = value;
  };
  const __out = {};
  for (const [__k, __v] of [["message", "hello from nodes2cloud"], ["githubVersioningTest", "true"]]) { __ccSetPath(__out, __k, __v); }
  return __out;
})();
        env.CC_ANALYTICS?.writeDataPoint({
          blobs: [ctx.workflow.id, ctx.execution.id, "set_1", "set", "success"],
          doubles: [Date.now() - __ccStart],
          indexes: [ctx.workflow.id],
        });
        __ccRunLog.push({ nodeId: "set_1", nodeType: "set", status: "success" });
        console.log("__CC_DEBUG__" + JSON.stringify({ nodeId: "set_1", phase: "success" }));
      }

      return new Response(JSON.stringify(ctx.output), { status: 202, headers: { "Content-Type": "application/json" } });
    } catch (err) {
      __ccStatus = "error";
      __ccError = err;
      throw err;
    } finally {
      await env.CC_RUN_KV?.put(
        `run:${ctx.workflow.id}:${ctx.execution.startedAt}:${ctx.execution.id}`,
        JSON.stringify({
          executionId: ctx.execution.id,
          workflowId: ctx.workflow.id,
          startedAt: ctx.execution.startedAt,
          status: __ccStatus,
          error: __ccError ? String(__ccError) : undefined,
          steps: __ccRunLog,
        }),
        { expirationTtl: 1209600 },
      );
    }
  },
};
